class LocationConstants {
  static const List<String> tagbilaranBarangays = [
    'Bool',
    'Booy',
    'Cabawan',
    'Cogon',
    'Dampas',
    'Dao',
    'Manga',
    'Mansasa',
    'Poblacion I',
    'Poblacion II',
    'Poblacion III',
    'San Isidro',
    'Taloto',
    'Tiptip',
    'Ubujan',
  ];

  static const List<String> balilihanBarangays = [
    'Baucan Norte',
    'Baucan Sur',
    'Boctol',
    'Boyog Norte',
    'Boyog Proper',
    'Boyog Sur',
    'Cabad',
    'Candasig',
    'Cantalid',
    'Cantomimbo',
    'Cogon',
    'Datag Norte',
    'Datag Sur',
    'Del Carmen Este (DCE) (Poblacion)',
    'Del Carmen Norte (DCN) (Poblacion)',
    'Del Carmen Sur (DCS) (Poblacion)',
    'Del Carmen Weste (DCW) (Poblacion)',
    'Del Rosario',
    'Dorol',
    'Haguilanan Grande',
    'Hanopol Este',
    'Hanopol Norte',
    'Hanopol Weste',
    'Magsija',
    'Maslog',
    'Sagasa',
    'Sal‑ing',
    'San Isidro',
    'San Roque',
    'Santo Niño',
    'Tagustusan',
  ];

  static const List<String> alburquerqueBarangays = [
    'Bahi',
    'San Agustin',
    'Basacdacu',
    'Santa Filomena',
    'Cantiguib',
    'Tagbuane',
    'Dangay',
    'Toril',
    'East Poblacion',
    'West Poblacion',
    'Ponong',
  ];

  static const List<String> aliciaBarangays = [
    'Cabantian',
    'Cagongcagong',
    'Cambaol',
    'Cayacay',
    'Del Monte',
    'Katipunan',
    'Lumbang',
    'Mahayag',
    'Poblacion',
    'San Isidro',
    'San Jose',
    'San Juan',
    'San Vicente',
    'Santo Niño',
    'Taytay',
  ];

  static const List<String> andaBarangays = [
    'Badiang',
    'Bantolinao',
    'Bato',
    'Bucal',
    'Cagting',
    'Calunasan',
    'Candabong',
    'Catagbacan',
    'Dagohoy',
    'Danao',
    'Dumaluan',
    'Lambog',
    'Lungsodaan',
    'Luy-a',
    'Poblacion',
    'Talisay',
  ];

  static const List<String> antequeraBarangays = [
    'Angilan',
    'Bantolinao',
    'Bicahan',
    'Bitaugan',
    'Bungahan',
    'Canlaas',
    'Cansibuan',
    'Can-omay',
    'Celing',
    'Danao',
    'Danicop',
    'Mag-aso',
    'Poblacion',
    'Quinapon-an',
    'Santo Rosario',
    'Tabuan',
    'Tagubaas',
    'Tupas',
    'Ubojan',
    'Viga',
    'Villa Aurora',
  ];

  static const List<String> baclayonBarangays = [
    'Cambanac',
    'Dasitam',
    'Buenaventura',
    'Guiwanon',
    'Landican',
    'Laya',
    'Libertad',
    'Montana',
    'Pamilacan',
    'Payahan',
    'Poblacion',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Taguihon',
    'Tanday',
  ];

  static const List<String> batuanBarangays = [
    'Alang-alang',
    'Aloja',
    'Behind the Clouds',
    'Bicbica',
    'Bunga',
    'Cagawasan',
    'Garcia',
    'Guinobatan',
    'Quirino',
    'Poblacion',
    'San Isidro',
  ];

  static const List<String> bienUnidoBarangays = [
    'Bacani',
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> bilarBarangays = [
    'Bacani',
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> buenavistaBarangays = [
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> calapeBarangays = [
    'Bacani',
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> candijayBarangays = [
    'Abihilan',
    'Anoling',
    'Boyo-an',
    'Cadapdapan',
    'Cambane',
    'Canawa',
    'Can-olin',
    'Cogtong',
    'La Union',
    'Luan',
    'Lungsodaan',
    'Mahangin',
    'Panadtaran',
    'Poblacion',
    'San Isidro',
    'San Vicente',
    'Santo Niño',
    'Tugas',
  ];

  static const List<String> carmenBarangays = [
    'Alegria',
    'Bicao',
    'Buenavista',
    'Buenos Aires',
    'Calatrava',
    'El Progreso',
    'Katipunan',
    'Luan',
    'Lumbang',
    'Magsaysay',
    'Mansasa',
    'Montesuerte',
    'Montevideo',
    'Nueva Fuerza',
    'Nueva Vida Este',
    'Nueva Vida Oeste',
    'Poblacion Norte',
    'Poblacion Sur',
    'San Isidro',
    'San Jose',
    'San Juan',
    'San Vicente',
    'Santo Niño',
    'Santo Rosario',
    'Santo Tomas',
    'Santo Niño',
    'Santo Niño Este',
    'Santo Niño Oeste',
  ];

  static const List<String> catigbianBarangays = [
    'Alegria',
    'Ambuan',
    'Baang',
    'Bagtic',
    'Bongbong',
    'Cambailan',
    'Candumayao',
    'Causwagan Norte',
    'Hagbuaya',
    'Haguilanan',
    'Kang-iras',
    'Libertad Sur',
    'Liboron',
    'Mahayag Norte',
    'Mahayag Sur',
    'Maitum',
    'Mantasida',
    'Poblacion',
    'Poblacion Weste',
    'Rizal',
    'Sinakayanan',
    'Triple Union',
  ];

  static const List<String> clarinBarangays = [
    'Anoling',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> corellaBarangays = [
    'Bacani',
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> cortesBarangays = [
    'De la Paz',
    'Fatima',
    'Loreto',
    'Lourdes',
    'Malayo Norte',
    'Malayo Sur',
    'Monserrat',
    'New Lourdes',
    'Patrocinio',
    'Poblacion',
    'Rosario',
    'Salvador',
    'San Roque',
    'Upper de la Paz',
  ];

  static const List<String> dagohoyBarangays = [
    'Babag',
    'Caluasan',
    'Candelaria',
    'Can-oling',
    'Colonia',
    'Mahayag',
    'Malitbog',
    'Mahayag',
    'San Miguel',
    'San Vicente',
    'Santo Rosario',
    'Villa Aurora',
    'Villa Anunciado',
    'Tabok',
    'Magtangtang',
  ];

  static const List<String> danaoBarangays = [
    'Cabatuan',
    'Cantubod',
    'Carbon',
    'Concepcion',
    'Dagohoy',
    'Hibale',
    'Magtangtang',
    'Nahud',
    'Poblacion',
    'Remedios',
    'San Carlos',
    'San Miguel',
    'Santa Fe',
    'Santo Niño',
    'Tabok',
    'Taming',
    'Villa Anunciado',
  ];

  static const List<String> dauisBarangays = [
    'Biking',
    'Bingag',
    'Catarman',
    'Dao',
    'Mayacabac',
    'Mariveles',
    'Poblacion',
    'San Isidro (Canlongon)',
    'Songculan',
    'Tabalong',
    'Totolan',
    'Tinago',
  ];

  static const List<String> dimiaoBarangays = [
    'Abihilan',
    'Anoling',
    'Boyo-an',
    'Cadapdapan',
    'Cambane',
    'Canawa',
    'Can-olin',
    'Cogtong',
    'La Union',
    'Luan',
    'Lungsodaan',
    'Mahangin',
    'Panadtaran',
    'Poblacion',
    'San Isidro',
    'San Vicente',
    'Santo Niño',
    'Tugas',
    'Bacani',
    'Baclayon',
    'Balili',
    'Bantolinao',
    'Bantug',
    'Cabantian',
    'Cagawasan',
    'Cagayan',
    'Cagayan Sur',
    'Cagawasan Sur',
    'Cagawasan Norte',
  ];

  static const List<String> dueroBarangays = [
    'Alejawan',
    'Angilan',
    'Bangwalog',
    'Cansuhay',
    'Duay',
    'Langkis',
    'Madua Norte',
    'Madua Sur',
    'Mambool',
    'Mawi',
    'Payao',
    'San Isidro',
    'Santa Cruz',
    'Taytay',
  ];

  static const List<String> garciaHernandezBarangays = [
    'Abijilan',
    'Antipolo',
    'Basiao',
    'Cagwang',
    'Calma',
    'Cambuyo',
    'Canayaon East',
    'Canayaon West',
    'Candanas',
    'Candulao',
    'Catmon',
    'Cayam',
    'Cupa',
    'Datag',
    'Estaca',
    'Libertad',
    'Lungsodaan East',
    'Lungsodaan West',
    'Malinao',
    'Manaba',
    'Pasong',
    'Poblacion East',
    'Poblacion West',
    'Sacaon',
    'Sampong',
    'Tabuan',
    'Togbongon',
    'Ulbujan East',
    'Ulbujan West',
    'Victoria',
  ];

  static const List<String> getafeBarangays = [
    'Alumar',
    'Banacon',
    'Buyog',
    'Cabasakan',
    'Campao Occidental',
    'Campao Oriental',
    'Cangmundo',
    'Carlos P. Garcia',
    'Corte Baud',
    'Handumon',
    'Jagoliao',
    'Jandayan Norte',
    'Jandayan Sur',
    'Mahanay',
    'Nasingin',
    'Pandanon',
    'Poblacion',
    'Saguise',
    'Salog',
    'San Jose',
    'Santo Niño',
    'Taytay',
    'Tugas',
    'Tulang',
  ];

  static const List<String> guindulmanBarangays = [
    'Basdio',
    'Bato',
    'Bayong',
    'Biabas',
    'Bulawan',
    'Cabantian',
    'Canhaway',
    'Cansiwang',
    'Casbu',
    'Catungawan Norte',
    'Catungawan Sur',
    'Guinacot',
    'Guio-ang',
    'Lombog',
    'Mayuga',
    'Sawang (Poblacion)',
    'Tabajan (Poblacion)',
    'Tabunok',
    'Trinidad',
  ];

  static const List<String> inabangaBarangays = [
    'Abijilan',
    'Antipolo',
    'Basiao',
    'Cagwang',
    'Calma',
    'Cambuyo',
    'Canayaon East',
    'Canayaon West',
    'Candanas',
    'Candulao',
    'Catmon',
    'Cayam',
    'Cupa',
    'Datag',
    'Estaca',
    'Libertad',
    'Lungsodaan East',
    'Lungsodaan West',
    'Malinao',
    'Manaba',
    'Pasong',
    'Poblacion East',
    'Poblacion West',
    'Sacaon',
    'Sampong',
    'Tabuan',
    'Togbongon',
    'Ulbujan East',
    'Ulbujan West',
    'Victoria',
  ];

  static const List<String> jagnaBarangays = [
    'Alejawan',
    'Balili',
    'Boctol',
    'Buyog',
    'Bunga Ilaya',
    'Bunga Mar',
    'Cabungaan',
    'Calabacita',
    'Cambugason',
    'Can-ipol',
    'Canjulao',
    'Cantagay',
    'Cantuyoc',
    'Can-uba',
    'Can-upao',
    'Faraon',
    'Ipil',
    'Kinagbaan',
    'Laca',
    'Larapan',
    'Lonoy',
    'Looc',
    'Malbog',
    'Mayana',
    'Naatang',
    'Nausok',
    'Odiong',
    'Pagina',
    'Pangdan',
    'Poblacion (Pondol)',
    'Tejero',
    'Tubod Mar',
    'Tubod Monte',
  ];

  static const List<String> lilaBarangays = [
    'Bagahupi',
    'Cahayag',
    'Calvario',
    'Candulang',
    'Catugasan',
    'Cayupo',
    'Cogon',
    'Genoveva',
    'Jalipa',
    'Macalingao',
    'Malinao East',
    'Malinao West',
    'Nagsulay',
    'Pagatpat',
    'Poblacion',
    'Taug',
  ];

  static const List<String> loayBarangays = [
    'Agape',
    'Allegría Bacani',
    'Bilaran',
    'Can-ato',
    'Concepcion',
    'Hinawanan',
    'Las Salinas Norte',
    'Las Salinas Sur',
    'Lila',
    'Nagsulay',
    'Palo',
    'Poblacion Ibaba',
    'Poblacion Ubos',
    'Sagnap',
    'Tangcasan Norte',
    'Tangcasan Sur',
    'Tayong',
    'Tugas',
    'Villalimpia',
    'Yanangan',
    'Alegria (Poblacion)',
    'Ilaud (Poblacion)',
    'Libertad (Poblacion)',
    'Lila (Poblacion)',
  ];

  static const List<String> lobocBarangays = [
    'Agape',
    'Bagumbayan',
    'Badiang',
    'Bahian',
    'Bil-isan',
    'Boc-ag',
    'Bonbon',
    'Bungahan',
    'Busay',
    'Calunasan Norte',
    'Calunasan Sur',
    'Camayan',
    'Concepcion',
    'Gala',
    'Gotozon',
    'Jimilian',
    'Kabasak',
    'Nataros',
    'Nueva Montana',
    'Oy',
    'Poblacion Sawang',
    'Poblacion Ubos',
    'Quinoguitan',
    'Sabac',
    'Sohor',
    'Tanday',
    'Tapon',
    'Ubojan',
  ];

  static const List<String> loonBarangays = [
    'Agahay',
    'Agape',
    'Agpo',
    'Bahan',
    'Bahi',
    'Bajo',
    'Banda',
    'Bantolinao',
    'Bao',
    'Basac',
    'Basdacu',
    'Baton',
    'Biga',
    'Bigo',
    'Bil-isan',
    'Bongco',
    'Bood',
    'Cabadug',
    'Cabug',
    'Cabugao',
    'Cahayag',
    'Calayugan Norte',
    'Calayugan Sur',
    'Can-aguing',
    'Candaigan',
    'Canhaway',
    'Canigaan',
    'Canmaag',
    'Canlusod',
    'Cansubayon',
    'Cantam-is Baslay',
    'Cantugod',
    'Cogon Norte',
    'Cogon Sur',
    'Cuasi',
    'Iliao',
    'Jalipa',
    'Jampang',
    'Jelicuon',
    'Jovellar',
    'Kabasacan',
    'Looc',
    'Looc Katipunan',
    'Lourdes',
    'Mabog',
    'Maitum',
    'Moalong',
    'Moto',
    'Nagtuang',
    'Panangatan',
    'Panhaytayon',
    'Pantudlan',
    'Poblacion',
    'Quinob-an',
    'Santal',
    'Sorog',
    'Suba',
    'Tabuan',
    'Talisay',
    'Tangnan',
    'Taytay',
    'Tultogan',
    'Tubigon (Ubay)',
    'Tubod',
    'Ubay',
    'Union',
    'Upo',
  ];

  static const List<String> mabiniBarangays = [
    'Abaca',
    'Bahan',
    'Bajo',
    'Balisong',
    'Baybay (Poblacion)',
    'Cabatang',
    'Cabidian',
    'Cam-unahan',
    'Can-andam',
    'Concepcion',
    'Del Mar',
    'Labugon',
    'Lawaan',
    'Lungsodaan',
    'Malijao',
    'Minol',
    'Pasanon',
    'Poblacion I (Pondol)',
    'Poblacion II (Pondol)',
    'San Isidro',
    'San Roque',
    'Tambis',
  ];

  static const List<String> maribojocBarangays = [
    'Aghao',
    'Aliguay',
    'Anislag',
    'Bayacabac',
    'Bood',
    'Busao',
    'Cabawan',
    'Candavid',
    'Datag',
    'Decolico',
    'Gabas',
    'Lagtangon',
    'Lantawan',
    'Pagsawitan',
    'Panghayaan',
    'Poblacion',
    'Pondol',
    'Puntod',
    'San Roque',
    'Tinibgan',
    'Toril',
    'Vevincio H. Tupas',
  ];

  static const List<String> panglaoBarangays = [
    'Bil-isan',
    'Bingag',
    'Bolod',
    'Danao',
    'Doljo',
    'Libertad',
    'Libaong',
    'Looc',
    'Malaya',
    'Poblacion',
  ];

  static const List<String> pilarBarangays = [
    'Alegria',
    'Aurora',
    'Bagacay',
    'Bagumbayan',
    'Bayong',
    'Catagda-an',
    'Del Pilar',
    'Estaca',
    'Inaghuban',
    'Lumbay',
    'Lundag',
    'New destined Place',
    'Poblacion',
    'Rizal',
    'San Carlos',
    'San Isidro',
    'San Miguel',
    'San Vicente',
    'Santa Fe',
    'Tabuan',
    'Tubod',
  ];

  static const List<String> presidentCarlosPGarciaBarangays = [
    'Aguining',
    'Basiao',
    'Bogo',
    'Bonbonon',
    'Campagao',
    'Can-upao',
    'Gaus',
    'Harigbo',
    'Hinlayagan Ilaya',
    'Lundag',
    'Mabini',
    'Magaspac',
    'Manaba',
    'Pitogo (Poblacion)',
    'Popo',
    'Saguise',
    'San Jose',
    'San Pablo',
    'Santo Niño',
    'Tugnao',
    'Tugas',
    'Union',
    'Yaray',
  ];

  static const List<String> sagbayanBarangays = [
    'Cabasan',
    'Cagawasan',
    'Calangahan',
    'Canmaya Centro',
    'Canmaya Diot',
    'Canmano',
    'Cansubay',
    'Dahican',
    'Dagnajoy',
    'Dait Sur',
    'Langtad',
    'Libertad',
    'Mabini',
    'Maningo',
    'Poblacion',
    'San Agustin',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Santa Catalina',
    'Santo Niño',
    'Sikatuna',
    'Tubo-tubo',
  ];

  static const List<String> sanIsidroBarangays = [
    'Abehilan',
    'Baryong Daan',
    'Baunos',
    'Cabanugan',
    'Caimbang',
    'Cambansag',
    'Candungao',
    'Cansague Norte',
    'Cansague Sur',
    'Causwagan Sur',
    'Masonoy',
    'Poblacion',
  ];

  static const List<String> sanMiguelBarangays = [
    'Bayongan',
    'Hagbuyo',
    'Bugang',
    'Caluasan',
    'Cabangahan',
    'Mahayag',
    'Kagawasan',
    'Poblacion',
    'Camanaga',
    'San Isidro',
    'Cambangay Norte',
    'San Jose',
    'Capayas',
    'San Vicente',
    'Corazon',
    'Santo Niño',
    'Garcia',
    'Tomoc',
  ];

  static const List<String> sevillaBarangays = [
    'Bayawahan',
    'Cabancalan',
    'Calbasa',
    'Calvario',
    'Cambagahan',
    'Candabong',
    'Concepcion',
    'Ewon',
    'Ginapol',
    'Magsaysay',
    'Poblacion',
    'Sakat',
    'Tambangan',
  ];

  static const List<String> sierraBullonesBarangays = [
    'Abachanan',
    'Anibongan',
    'Cagawasan',
    'Cagayan',
    'Can-umay',
    'Casilay',
    'Dalipe',
    'Duron',
    'Hinaganay',
    'La Union',
    'Lactudan',
    'Magsaysay',
    'Nueva Montana',
    'Pagahat',
    'Poblacion',
    'Sag-umay',
    'Salvador',
    'San Agustin',
    'San Isidro',
    'San Jose',
    'Villa Garcia',
    'Villahermosa',
  ];

  static const List<String> sikatunaBarangays = [
    'Abucay Norte',
    'Abucay Sur',
    'Badiang',
    'Cagawasan',
    'Cambatugay',
    'Libertad',
    'Poblacion I',
    'Poblacion II',
    'Santo Niño',
    'Talisay',
  ];

  static const List<String> talibonBarangays = [
    'Bagacay',
    'Calituban',
    'Camangahan',
    'Cataban',
    'Das-ag',
    'Hinlayagan Ilaya',
    'Ilihan',
    'Magsaysay',
    'Nocnocan',
    'Poblacion',
    'Rocdug',
    'San Agustin',
    'San Jose',
    'San Roque',
    'San Salvador',
    'Santa Catalina',
    'Santo Niño',
    'Sikatuna',
    'Tugop',
  ];

  static const List<String> trinidadBarangays = [
    'Banahao',
    'Bayabas',
    'Bihang',
    'Gala',
    'Hinlayagan Ilaud',
    'Hinlayagan Ilaya',
    'Kauswagan',
    'Kinagbaan',
    'La Union',
    'Looc',
    'Mabuhay',
    'San Isidro',
    'San Jose',
    'San Vicente',
    'Santo Niño',
    'Sikatuna',
    'Tagum Norte',
    'Tagum Sur',
    'Tugop',
    'Ubaid',
  ];

  static const List<String> tubigonBarangays = [
    'Bagacay',
    'Bahay-bahay',
    'Bilangbilangan',
    'Bosongon',
    'Buenos Aires',
    'Buanan',
    'Cabait',
    'Cabul-anonan',
    'Cabulihan',
    'Cagawasan',
    'Cagawitan',
    'Cahayag',
    'Candaol',
    'Can-ezo',
    'Cansangkay',
    'Catan-agan',
    'Gala',
    'Genonocan',
    'Giporlo',
    'Lajong',
    'Libertad',
    'Lombog',
    'Macaas',
    'Mabini',
    'Mampik',
    'Panaytayon',
    'Poblacion',
    'Pook',
    'Potohan',
    'Talisay',
    'Tanda',
    'Taway',
    'Tinangnan',
    'Ubay',
  ];

  static const List<String> ubayBarangays = [
    'Aloja',
    'Badiang',
    'Bagong-silang',
    'Baguhan',
    'Bay-ang',
    'Bood',
    'Calangigan',
    'Calanggaman',
    'Calayugan Centro',
    'Calayugan Norte',
    'Calayugan Sur',
    'Camalig',
    'Camambugan',
    'Cantato',
    'Casate',
    'Cuya',
    'Danao',
    'Fatima',
    'Faraon',
    'Gabat',
    'Hambabauran',
    'Hingotanan East',
    'Hingotanan West',
    'Humayhumay',
    'Ilihan',
    'Inabanga',
    'Jalijali',
    'Kagawasan',
    'Kanguha',
    'Lantong',
    'Lawis',
    'Looc',
    'Lundag',
    'Lower Potot',
    'Nabuad',
    'Pasil',
    'Poblacion',
    'San Isidro',
    'San Pascual',
    'Sinandigan',
    'Tapal',
    'Tapon',
    'Tubo',
    'Union',
  ];

  static const List<String> valenciaBarangays = [
    'Abaca',
    'Anonang',
    'Anoyon',
    'Badiang',
    'Buyog',
    'Cambays',
    'Canlusong',
    'Canmanico',
    'Cansibao',
    'Catugasan',
    'Jubay',
    'Lantang',
    'Limocón',
    'Looc',
    'Lutac',
    'Magsaysay',
    'Manapol',
    'Nagsulay',
    'Omjon',
    'Pandan',
    'Poblacion',
    'Sacaon',
    'San Agustin',
    'San Isidro',
    'Santa Cruz',
    'Santo Niño',
    'Simang',
    'Taug',
    'Taytay',
    'Tucod',
    'Von Kiela',
  ];

  static const List<String> boholMunicipalities = [
    'Tagbilaran',
    'Balilihan',
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'President Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ];

  static const Map<String, List<String>> municipalityBarangays = {
    'Tagbilaran': tagbilaranBarangays,
    'Balilihan': balilihanBarangays,
    'Alburquerque': alburquerqueBarangays,
    'Alicia': aliciaBarangays,
    'Anda': andaBarangays,
    'Antequera': antequeraBarangays,
    'Baclayon': baclayonBarangays,
    'Batuan': batuanBarangays,
    'Bien Unido': bienUnidoBarangays,
    'Bilar': bilarBarangays,
    'Buenavista': buenavistaBarangays,
    'Calape': calapeBarangays,
    'Candijay': candijayBarangays,
    'Carmen': carmenBarangays,
    'Catigbian': catigbianBarangays,
    'Clarin': clarinBarangays,
    'Corella': corellaBarangays,
    'Cortes': cortesBarangays,
    'Dagohoy': dagohoyBarangays,
    'Danao': danaoBarangays,
    'Dauis': dauisBarangays,
    'Dimiao': dimiaoBarangays,
    'Duero': dueroBarangays,
    'Garcia Hernandez': garciaHernandezBarangays,
    'Getafe': getafeBarangays,
    'Guindulman': guindulmanBarangays,
    'Inabanga': inabangaBarangays,
    'Jagna': jagnaBarangays,
    'Lila': lilaBarangays,
    'Loay': loayBarangays,
    'Loboc': lobocBarangays,
    'Loon': loonBarangays,
    'Mabini': mabiniBarangays,
    'Maribojoc': maribojocBarangays,
    'Panglao': panglaoBarangays,
    'Pilar': pilarBarangays,
    'President Carlos P. Garcia': presidentCarlosPGarciaBarangays,
    'Sagbayan': sagbayanBarangays,
    'San Isidro': sanIsidroBarangays,
    'San Miguel': sanMiguelBarangays,
    'Sevilla': sevillaBarangays,
    'Sierra Bullones': sierraBullonesBarangays,
    'Sikatuna': sikatunaBarangays,
    'Talibon': talibonBarangays,
    'Trinidad': trinidadBarangays,
    'Tubigon': tubigonBarangays,
    'Ubay': ubayBarangays,
    'Valencia': valenciaBarangays,
  };

  static List<String> getSortedMunicipalities() {
    final municipalities = boholMunicipalities.toSet().toList();
    municipalities.sort();
    return municipalities;
  }

  static List<String> getBarangaysForMunicipality(String municipality) {
    final barangays = municipalityBarangays[municipality] ?? [];
    final sortedBarangays = barangays.toList()..sort();
    return sortedBarangays;
  }
}
