class LocationConstants {
  static const List<String> tagbilaranBarangays = [
    'Bool',
    'Booy',
    'Cabawan',
    'Cogon',
    'Dampas',
    'Dao',
    'Manga',
    'Mansasa',
    'Poblacion I',
    'Poblacion II',
    'Poblacion III',
    'San Isidro',
    'Taloto',
    'Tiptip',
    'Ubujan',
  ];

  static const List<String> balilihanBarangays = [
    'Baucan Norte',
    'Baucan Sur',
    'Boctol',
    'Boyog Norte',
    'Boyog Proper',
    'Boyog Sur',
    'Cabad',
    'Candasig',
    'Cantalid',
    'Cantomimbo',
    'Cogon',
    'Datag Norte',
    'Datag Sur',
    'Del Carmen Este (DCE) (Poblacion)',
    'Del Carmen Norte (DCN) (Poblacion)',
    'Del Carmen Sur (DCS) (Poblacion)',
    'Del Carmen Weste (DCW) (Poblacion)',
    'Del Rosario',
    'Dorol',
    'Haguilanan Grande',
    'Hanopol Este',
    'Hanopol Norte',
    'Hanopol Weste',
    'Magsija',
    'Maslog',
    'Sagasa',
    'Sal‑ing',
    'San Isidro',
    'San Roque',
    'Santo Niño',
    'Tagustusan',
  ];

  static const List<String> alburquerqueBarangays = [
    'Bahi',
    'San Agustin',
    'Basacdacu',
    'Santa Filomena',
    'Cantiguib',
    'Tagbuane',
    'Dangay',
    'Toril',
    'East Poblacion',
    'West Poblacion',
    'Ponong',
  ];

  static const List<String> aliciaBarangays = [
    'Cabatang',
    'Cagongcagong',
    'Cambaol',
    'Cayacay',
    'Del Monte',
    'Katipunan',
    'La Hacienda',
    'Mahayag',
    'Napo',
    'Pagahat',
    'Poblacion (Calingganay)',
    'Progreso',
    'Putlongcam',
    'Sudlon (Omhon)',
    'Untaga',
  ];

  static const List<String> andaBarangays = [
    'Almaria',
    'Bacong',
    'Badiang',
    'Buenasuerte',
    'Candabong',
    'Casica',
    'Katipunan',
    'Linawan',
    'Lundag',
    'Poblacion',
    'Santa Cruz',
    'Suba',
    'Talisay',
    'Tanod',
    'Tawid',
    'Virgen',
  ];

  static const List<String> antequeraBarangays = [
    'Angilan',
    'Bantolinao',
    'Bicahan',
    'Bitaugan',
    'Bungahan',
    'Canlaas',
    'Cansibuan',
    'Can-omay',
    'Celing',
    'Danao',
    'Danicop',
    'Mag-aso',
    'Poblacion',
    'Quinapon-an',
    'Santo Rosario',
    'Tabuan',
    'Tagubaas',
    'Tupas',
    'Ubojan',
    'Viga',
    'Villa Aurora (Canoc-oc)',
  ];

  static const List<String> baclayonBarangays = [
    'Cambanac',
    'Dasitam',
    'Buenaventura',
    'Guiwanon',
    'Landican',
    'Laya',
    'Libertad',
    'Montana',
    'Pamilacan',
    'Payahan',
    'Poblacion',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Taguihon',
    'Tanday',
  ];

  static const List<String> batuanBarangays = [
    'Aloja',
    'Behind The Clouds (San Jose)',
    'Cabacnitan',
    'Cambacay',
    'Cantigdas',
    'Garcia',
    'Janlud',
    'Poblacion Norte',
    'Poblacion Sur',
    'Poblacion Vieja',
    'Quezon',
    'Quirino',
    'Rizal',
    'Rosariohan',
    'Santa Cruz',
  ];

  static const List<String> bienUnidoBarangays = [
    'Bilangbilangan Dako',
    'Bilangbilangan Diot',
    'Hingotanan East',
    'Hingotanan West',
    'Liberty',
    'Malingin',
    'Mandawa',
    'Maomawan',
    'Nueva Esperanza',
    'Nueva Estrella',
    'Pinamgo',
    'Poblacion (Bien Unido)',
    'Puerto San Pedro',
    'Sagasa',
    'Tuboran',
  ];

  static const List<String> bilarBarangays = [
    'Bonifacio',
    'Bugang Norte',
    'Bugang Sur',
    'Cabacnitan (Magsaysay)',
    'Cambigsi',
    'Campagao',
    'Cansumbol',
    'Dagohoy',
    'Owac',
    'Poblacion',
    'Quezon',
    'Riverside',
    'Rizal',
    'Roxas',
    'Subayon',
    'Villa Aurora',
    'Villa Suerte',
    'Yanaya',
    'Zamora',
  ];

  static const List<String> buenavistaBarangays = [
    'Anonang',
    'Asinan',
    'Bago',
    'Baluarte',
    'Bantuan',
    'Bato',
    'Bonotbonot',
    'Bugaong',
    'Cambuhat',
    'Cambus-oc',
    'Cangawa',
    'Cantomugcad',
    'Cantores',
    'Cantuba',
    'Catigbian',
    'Cawag',
    'Cruz',
    'Dait',
    'Eastern Cabul-an',
    'Hunan',
    'Lapacan Norte',
    'Lapacan Sur',
    'Lubang',
    'Lusong (Plateau)',
    'Magkaya',
    'Merryland',
    'Nueva Granada',
    'Nueva Montana',
    'Overland',
    'Panghagban',
    'Poblacion',
    'Puting Bato',
    'Rufo Hill',
    'Sweetland',
    'Western Cabul-an',
  ];

  static const List<String> calapeBarangays = [
    'Abucayan Norte',
    'Abucayan Sur',
    'Banlasan',
    'Bentig',
    'Binogawan',
    'Bonbon',
    'Cabayugan',
    'Cabudburan',
    'Calunasan',
    'Camias',
    'Canguha',
    'Catmonan',
    'Desamparados (Poblacion)',
    'Kahayag',
    'Kinabag-an',
    'Labuon',
    'Lawis',
    'Liboron',
    'Lo-oc',
    'Lomboy',
    'Lucob',
    'Madangog',
    'Magtongtong',
    'Mandaug',
    'Mantatao',
    'Sampoangon',
    'San Isidro',
    'Santa Cruz (Poblacion)',
    'Sohoton',
    'Talisay',
    'Tinibgan',
    'Tultugan',
    'Ulbujan',
  ];

  static const List<String> candijayBarangays = [
    'Abihilan',
    'Anoling',
    'Boyo-an',
    'Cadapdapan',
    'Cambane',
    'Can-olin',
    'Canawa',
    'Cogtong',
    'La Union',
    'Luan',
    'Lungsoda-an',
    'Mahangin',
    'Pagahat',
    'Panadtaran',
    'Panas',
    'Poblacion',
    'San Isidro',
    'Tambongan',
    'Tawid',
    'Tugas',
    'Tubod (Tres Rosas)',
  ];

  static const List<String> carmenBarangays = [
    'Alegria',
    'Bicao',
    'Buenavista',
    'Buenos Aires',
    'Calatrava',
    'El Progreso',
    'El Salvador',
    'Guadalupe',
    'Katipunan',
    'La Libertad',
    'La Paz',
    'La Salvacion',
    'La Victoria',
    'Matin-ao',
    'Montehermoso',
    'Montesuerte',
    'Montesunting',
    'Montevideo',
    'Nueva Fuerza',
    'Nueva Vida Este',
    'Nueva Vida Sur',
    'Nueva Vida Norte',
    'Poblacion Norte',
    'Poblacion Sur',
    'Tambo-an',
    'Vallehermoso',
    'Villaflor',
    'Villafuerte',
    'Villarcayo',
  ];

  static const List<String> catigbianBarangays = [
    'Alegria',
    'Ambuan',
    'Baang',
    'Bagtic',
    'Bongbong',
    'Cambailan',
    'Candumayao',
    'Kang-iras',
    'Causwagan Norte',
    'Hagbuaya',
    'Haguilanan',
    'Libertad Sur',
    'Liboron',
    'Mahayag Norte',
    'Mahayag Sur',
    'Maitum',
    'Mantasida',
    'Poblacion',
    'Poblacion Weste',
    'Rizal',
    'Sinakayanan',
    'Triple Union',
  ];

  static const List<String> clarinBarangays = [
    'Bacani',
    'Bogtongbod',
    'Bonbon',
    'Bontud',
    'Buacao',
    'Buangan',
    'Cabog',
    'Caboy',
    'Caluwasan',
    'Candajec',
    'Cantoyoc',
    'Comaang',
    'Danahao',
    'Katipunan',
    'Lajog',
    'Mataub',
    'Nahawan',
    'Poblacion Centro',
    'Poblacion Norte',
    'Poblacion Sur',
    'Tangaran',
    'Tontunan',
    'Tubod',
    'Villaflor',
  ];

  static const List<String> corellaBarangays = [
    'Anislag',
    'Canangca-an',
    'Canapnapan',
    'Cancatac',
    'Pandol',
    'Poblacion',
    'Sambog',
    'Tanday',
  ];

  static const List<String> cortesBarangays = [
    'De la Paz',
    'Fatima',
    'Loreto',
    'Lourdes',
    'Malayo Norte',
    'Malayo Sur',
    'Monserrat',
    'New Lourdes',
    'Patrocinio',
    'Poblacion',
    'Rosario',
    'Salvador',
    'San Roque',
    'Upper de la Paz',
  ];

  static const List<String> dagohoyBarangays = [
    'Babag',
    'Cagawasan',
    'Cagawitan',
    'Caluasan',
    'Candelaria',
    'Can-oling',
    'Estaca',
    'La Esperanza',
    'Mahayag',
    'Malitbog',
    'Poblacion',
    'San Miguel',
    'San Vicente',
    'Santa Cruz',
    'Villa Aurora',
  ];

  static const List<String> danaoBarangays = [
    'Villa Anunciado',
    'Awihaw',
    'Cagawasan',
    'Camanaga',
    'Cantubod',
    'Dagohoy',
    'Hagbuaya',
    'Magsaysay',
    'Malitbog',
    'Nahawan',
    'Poblacion',
    'San Carlos',
    'San Miguel',
    'Santa Fe',
    'Tabok',
    'Tubtubon',
    'Villa Suerte',
  ];

  static const List<String> dauisBarangays = [
    'Biking',
    'Bingag',
    'San Isidro (Canlongon)',
    'Catarman',
    'Dao',
    'Mayacabac',
    'Poblacion',
    'Songculan',
    'Tabalong',
    'Tinago',
    'Totolan',
    'Mariveles',
  ];

  static const List<String> dimiaoBarangays = [
    'Abihid',
    'Alemania',
    'Baguhan',
    'Bakilid',
    'Balbalan',
    'Banban',
    'Bauhugan',
    'Bilisan',
    'Cabagakian',
    'Cabanbanan',
    'Cadap-agan',
    'Cambacol',
    'Cambayaon',
    'Canhayupon',
    'Canlambong',
    'Casingan',
    'Catugasan',
    'Datag',
    'Guindaguitan',
    'Guingoyuran',
    'Ile',
    'Lapsaon',
    'Limokon Ilaod',
    'Limokon Ilaya',
    'Luyo',
    'Malijao',
    'Oac',
    'Pagsa',
    'Pangihawan',
    'Sawang',
    'Puangyuta',
    'Tangohay',
    'Taongon Cabatuan',
    'Tawid Bitaog',
    'Taongon Can-andam',
  ];

  static const List<String> dueroBarangays = [
    'Alejawan',
    'Angilan',
    'Anibongan',
    'Bangwalog',
    'Cansuhay',
    'Danao',
    'Duay',
    'Guinsularan',
    'Imelda',
    'Itum',
    'Langkis',
    'Lobogon',
    'Madua Norte',
    'Madua Sur',
    'Mambool',
    'Mawi',
    'Payao',
    'San Antonio (Pob.)',
    'San Isidro',
    'San Pedro',
    'Tatay',
  ];

  static const List<String> garciaHernandezBarangays = [
    'Abijilan',
    'Antipolo',
    'Basiao',
    'Cagwang',
    'Calma',
    'Cambuyo',
    'Canayaon East',
    'Canayaon West',
    'Candanas',
    'Candulao',
    'Catmon',
    'Cayam',
    'Cupa',
    'Datag',
    'Estaca',
    'Libertad',
    'Lungsodaan East',
    'Lungsodaan West',
    'Malinao',
    'Manaba',
    'Pasong',
    'Poblacion East',
    'Poblacion West',
    'Sacaon',
    'Sampong',
    'Tabuan',
    'Togbongon',
    'Ulbujan East',
    'Ulbujan West',
    'Victoria',
  ];

  static const List<String> getafeBarangays = [
    'Alumar',
    'Banacon',
    'Buyog',
    'Cabasakan',
    'Campao Occidental',
    'Campao Oriental',
    'Cangmundo',
    'Carlos P. Garcia',
    'Corte Baud',
    'Handumon',
    'Jagoliao',
    'Jandayan Norte',
    'Jandayan Sur',
    'Mahanay Island',
    'Nasingin',
    'Pandanon',
    'Poblacion',
    'Saguise',
    'Salog',
    'San Jose',
    'Santo Niño',
    'Taytay',
    'Tugas',
    'Tulang',
  ];

  static const List<String> guindulmanBarangays = [
    'Basdio',
    'Bato',
    'Bayong',
    'Biabas',
    'Bulawan',
    'Cabantian',
    'Canhaway',
    'Cansiwang',
    'Casbu',
    'Catungawan Norte',
    'Catungawan Sur',
    'Guinacot',
    'Guio-ang',
    'Lombog',
    'Mayuga',
    'Sawang',
    'Tabajan (Pob.)',
    'Tabunok',
    'Trinidad',
  ];

  static const List<String> inabangaBarangays = [
    'Anonang',
    'Bahan',
    'Badiang',
    'Baguhan',
    'Banahao',
    'Baogo',
    'Bugang',
    'Cagawasan',
    'Cagayan',
    'Cambitoon',
    'Canlinte',
    'Cawayan',
    'Cogon',
    'Cuaming',
    'Dagnawan',
    'Dagohoy',
    'Dait Sur',
    'Datag',
    'Fatima',
    'Hambongan',
    'Ilaud',
    'Ilaya',
    'Ilihan',
    'Lapacan Norte',
    'Lapacan Sur',
    'Lawis',
    'Liloan Norte',
    'Liloan Sur',
    'Lomboy',
    'Lonoy Cainsican',
    'Lonoy Roma',
    'Lutao',
    'Luyo',
    'Mabuhay',
    'Ma. Rosario',
    'Nabuad',
    'Napo',
    'Ondol',
    'Poblacion',
    'Riverside',
    'Saa',
    'San Isidro',
    'San Jose',
    'Santo Niño',
    'Santo Rosario',
    'Sua',
    'Tambook',
    'Tungod',
    'Ubujan',
    'Uog',
  ];

  static const List<String> jagnaBarangays = [
    'Alejawan',
    'Balili',
    'Boctol',
    'Bunga Ilaya',
    'Bunga Mar',
    'Buyog',
    'Cabunga-an',
    'Calabacita',
    'Cambugason',
    'Can-ipol',
    'Canjulao',
    'Cantagay',
    'Cantuyoc',
    'Canuba',
    'Can-upao',
    'Faraon',
    'Ipil',
    'Kinagbaan',
    'Laca',
    'Larapan',
    'Lonoy',
    'Looc',
    'Malbog',
    'Mayana',
    'Naatang',
    'Nausok',
    'Odiong',
    'Pagina',
    'Pangdan',
    'Poblacion',
    'Tejero',
    'Tubod Mar',
    'Tubod Monte',
  ];

  static const List<String> lilaBarangays = [
    'Banban',
    'Bonkokan Ilaya',
    'Bonkokan Ubos',
    'Calvario',
    'Candulang',
    'Catugasan',
    'Cayupo',
    'Cogon',
    'Jambawan',
    'La Fortuna',
    'Lomanoy',
    'Macalingan',
    'Malinao East',
    'Malinao West',
    'Nagsulay',
    'Poblacion',
    'Taug',
    'Tiguis',
  ];

  static const List<String> loayBarangays = [
    'Agape',
    'Alegria Norte',
    'Alegria Sur',
    'Bonbon',
    'Botoc Occidental',
    'Botoc Oriental',
    'Cambaquiz',
    'Can-ipol',
    'Canuba',
    'Catagbacan Norte',
    'Catagbacan Sur',
    'Cogon Norte',
    'Cogon Sur',
    'Cuasi',
    'Owad',
    'Poblacion',
    'Riverside',
    'San Isidro',
    'San Juan',
    'Santa Fe',
    'Tag-ilan',
    'Talib',
    'Tud-an',
    'Villa Aurora',
  ];

  static const List<String> lobocBarangays = [
    'Agape',
    'Bagumbayan',
    'Bahi-an',
    'Bahi',
    'Bil-isan',
    'Bonbon',
    'Bugho',
    'Bungahan',
    'Busay',
    'Calunasan Norte',
    'Calunasan Sur',
    'Camayaan',
    'Candasagan',
    'Gon-ob',
    'Gongonan',
    'Gotozon',
    'Jimilian',
    'Mag-Aso',
    'Nueva Vida',
    'Oy',
    'Poblacion Sawang',
    'Poblacion Ubos',
    'Quinoguitan',
    'Sabac',
    'Sohoton',
    'Tanday',
    'Tapon',
    'Ubojan',
  ];

  static const List<String> loonBarangays = [
    'Agsoso',
    'Badbad Occidental',
    'Badbad Oriental',
    'Bagacay Katipunan',
    'Bagacay Kawayan',
    'Bagacay Saong',
    'Bahi',
    'Basac',
    'Basdacu',
    'Basdio',
    'Biasong',
    'Bongco',
    'Bugho',
    'Cabacongan',
    'Cabadug',
    'Cabug',
    'Calayugan Norte',
    'Calayugan Sur',
    'Canmaag',
    'Cambaquiz',
    'Campatud',
    'Candaigan',
    'Canhangdon Occidental',
    'Canhangdon Oriental',
    'Canigaan',
    'Canmanoc',
    'Cansuagwit',
    'Cansubayon',
    'Catagbacan Handig',
    'Catagbacan Norte',
    'Catagbacan Sur',
    'Cantam-is Bago',
    'Cantaongon',
    'Cantumocad',
    'Cantam-is Baslay',
    'Cogon Norte',
    'Cogon Sur',
    'Cuasi',
    'Genomoan',
    'Lintuan',
    'Looc',
    'Mocpoc Norte',
    'Mocpoc Sur',
    'Nagtuang',
    'Napo',
    'Nueva Vida',
    'Panangquilon',
    'Pantudlan',
    'Pig-ot',
    'Moto Norte',
    'Moto Sur',
    'Pondol',
    'Quinobcoban',
    'Sondol',
    'Song-on',
    'Talisay',
    'Tan-awan',
    'Tangnan',
    'Taytay',
    'Ticugan',
    'Tiwi',
    'Tontonan',
    'Tubodacu',
    'Tubodio',
    'Tubuan',
    'Ubayon',
    'Ubojan',
  ];

  static const List<String> mabiniBarangays = [
    'Abaca',
    'Abad Santos',
    'Aguipo',
    'Baybayon',
    'Bulawan',
    'Cabidian',
    'Cawayanan',
    'Concepcion (Banlas)',
    'Del Mar',
    'Lungsodaan',
    'Marcelo',
    'Minol',
    'Paraiso',
    'Poblacion I',
    'Poblacion II',
    'San Isidro',
    'San Jose',
    'San Rafael',
    'San Roque (Cabulao)',
    'Tambo',
    'Tangkigan',
    'Valaga',
  ];

  static const List<String> maribojocBarangays = [
    'Agahay',
    'Aliguay',
    'Anislag',
    'Bayacabac',
    'Bood',
    'Busao',
    'Cabawan',
    'Candavid',
    'Dipatlong',
    'Guiwanon',
    'Jandig',
    'Lagtangon',
    'Lincod',
    'Pagnitoan',
    'Poblacion',
    'Punsod',
    'Punta Cruz',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Tinibgan',
    'Toril',
  ];

  static const List<String> panglaoBarangays = [
    'Bil-isan',
    'Bolod',
    'Danao',
    'Doljo',
    'Libaong',
    'Looc',
    'Lourdes',
    'Poblacion',
    'Tangnan',
    'Tawala',
  ];

  static const List<String> pilarBarangays = [
    'Aurora',
    'Bagacay',
    'Bagumbayan',
    'Bayong',
    'Buen asuerte',
    'Cagawasan',
    'Cansungay',
    'Catagda-an',
    'Del Pilar',
    'Estaca',
    'Ilaud',
    'Inaghuban',
    'La Suerte',
    'Lumbay',
    'Lundag',
    'Pamacsalan',
    'Poblacion',
    'Rizal',
    'San Carlos',
    'San Isidro',
    'San Vicente',
  ];

  static const List<String> presidentCarlosPGarciaBarangays = [
    'Aguining',
    'Basiao',
    'Baud',
    'Bayog',
    'Bogo',
    'Bonbonon',
    'Butan',
    'Campamanog',
    'Canmangao',
    'Gaus',
    'Kabangkalan',
    'Lapinig',
    'Lipata',
    'Poblacion',
    'Popoo',
    'Saguise',
    'San Jose (Tawid)',
    'San Vicente',
    'Santo Rosario',
    'Tilmobo',
    'Tugas',
    'Tugnao',
    'Villa Milagrosa',
  ];

  static const List<String> sagbayanBarangays = [
    'Calangahan',
    'Canmano',
    'Canmaya Centro',
    'Canmaya Diot',
    'Dagnawan',
    'Kabasacan',
    'Kagawasan',
    'Katipunan',
    'Langtad',
    'Libertad Norte',
    'Libertad Sur',
    'Mantalongon',
    'Poblacion',
    'Sagbayan Sur',
    'San Agustin',
    'San Antonio',
    'San Isidro',
    'San Ramon',
    'San Roque',
    'San Vicente Norte',
    'San Vicente Sur',
    'Santa Catalina',
    'Santa Cruz',
    'Ubojan',
  ];

  static const List<String> sanIsidroBarangays = [
    'Abehilan',
    'Baryong Daan',
    'Baunos',
    'Cabanugan',
    'Caimbang',
    'Cambansag',
    'Candungao',
    'Cansague Norte',
    'Cansague Sur',
    'Causwagan Sur',
    'Masonoy',
    'Poblacion',
  ];

  static const List<String> sanMiguelBarangays = [
    'Bayongan',
    'Bugang',
    'Cabangahan',
    'Caluasan',
    'Fatima',
    'Mabuhay',
    'Manalongon',
    'Milagrosa',
    'Nagbinlod',
    'Nagbalaye',
    'Pinamgo',
    'Poblacion',
    'San Agustin',
    'San Antonio',
    'San Isidro',
    'San Ramon',
    'San Roque',
    'San Vicente Norte',
    'San Vicente Sur',
    'Santa Catalina',
    'Santa Cruz',
    'Ubojan',
  ];

  static const List<String> sevillaBarangays = [
    'Bayawahan',
    'Cabancalan',
    'Calinga-an',
    'Calinginan Norte',
    'Calinginan Sur',
    'Cambagui',
    'Ewon',
    'Guinob-an',
    'Lagtangan',
    'Licolico',
    'Lobgob',
    'Magsaysay',
    'Poblacion',
  ];

  static const List<String> sierraBullonesBarangays = [
    'Abachanan',
    'Anibongan',
    'Bugsoc',
    'Canlangit',
    'Canta-ub',
    'Casilay',
    'Danicop',
    'Dusita',
    'Cahayag',
    'La Union',
    'Lataban',
    'Magsaysay',
    'Matin-ao',
    'Nan-od',
    'Poblacion',
    'Salvador',
    'San Agustin',
    'San Isidro',
    'San Jose',
    'San Juan',
    'Santa Cruz',
    'Villa Garcia',
  ];

  static const List<String> sikatunaBarangays = [
    'Abucay Norte',
    'Abucay Sur',
    'Badiang',
    'Bahaybahay',
    'Cambuac Norte',
    'Cambuac Sur',
    'Can-agong',
    'Libjo',
    'Poblacion I',
    'Poblacion II',
  ];

  static const List<String> talibonBarangays = [
    'Bagacay',
    'Balintawak',
    'Burgos',
    'Busalian',
    'Calituban',
    'Cataban',
    'Guindacpan',
    'Magsaysay',
    'Mahanay',
    'Nocnocan',
    'Poblacion',
    'Rizal',
    'San Agustin',
    'San Carlos',
    'San Francisco',
    'San Isidro',
    'San Jose',
    'San Pedro',
    'San Roque',
    'Santo Niño',
  ];

  static const List<String> trinidadBarangays = [
    'Banlasan',
    'Bongbong',
    'Catoogan',
    'Guinobatan',
    'Hinlayagan Ilaud',
    'Hinlayagan Ilaya',
    'Kauswagan',
    'Kinan-oan',
    'La Union',
    'La Victoria',
    'Mabuhay Cabigohan',
    'Mahagbu',
    'Manuel M. Roxas',
    'Poblacion',
    'San Isidro',
    'San Vicente',
    'Santo Tomas',
    'Soom',
    'Tagum Norte',
    'Tagum Sur',
  ];

  static const List<String> tubigonBarangays = [
    'Bagongbanwa',
    'Bunacan',
    'Banlasan',
    'Batasan',
    'Bilangbilangan',
    'Bosongon',
    'Buenos Aires',
    'Cabulihan',
    'Cahayag',
    'Cawayanan',
    'Centro (Poblacion)',
    'Genonocan',
    'Guiwanon',
    'Ilihan Norte',
    'Ilihan Sur',
    'Libertad',
    'Macaas',
    'Mocaboc Island',
    'Matabao',
    'Panadtaran',
    'Panaytayon',
    'Pandan',
    'Pangapasan',
    'Pinayagan Norte',
    'Pinayagan Sur',
    'Pooc Occidental (Poblacion)',
    'Pooc Oriental (Poblacion)',
    'Potohan',
    'Talenceras',
    'Tan-awan',
    'Tinangnan',
    'Ubay Island',
    'Ubojan',
    'Villanueva',
  ];

  static const List<String> ubayBarangays = [
    'Achila',
    'Bay-ang',
    'Biabas',
    'Benliw',
    'Bongbong',
    'Bood',
    'Buenavista',
    'Cagting',
    'Camali-an',
    'Camambugan',
    'Canlinao',
    'Fatima',
    'Gabi',
    'Governor Boyles',
    'Hambabauran',
    'Humayhumay',
    'Ilihan',
    'Juagdan',
    'Katarungan',
    'Lomangog',
    'Los Angeles',
    'Pangpang',
    'Poblacion',
    'San Francisco',
    'San Isidro',
    'San Pascual',
    'San Vicente',
    'Sentinila',
    'Tipolo',
    'Tapal',
    'Tapon',
    'Tharsis',
    'Tintinan',
    'Tubog',
    'Tuboran',
    'Ubujan',
    'Union',
    'Villa Anunciado',
    'Villa Teresita',
    'Pag-asa',
    'Imelda',
    'Calanggaman',
    'Baye',
    'Bulilis',
    'San Jose',
  ];

  static const List<String> valenciaBarangays = [
    'Adlawan',
    'Anas',
    'Anonang',
    'Anoyon',
    'Balingasao',
    'Banderahan (Upper Ginopolan)',
    'Botong',
    'Buyog',
    'Canduao Occidental',
    'Canduao Oriental',
    'Canlusong',
    'Canmanico',
    'Cansibao',
    'Catug-a',
    'Cutcutan',
    'Danao',
    'Genoveva',
    'Ginopolan (Ginopolan Proper)',
    'La Victoria',
    'Lantang',
    'Limocon',
    'Loctob',
    'Magsaysay',
    'Marawis',
    'Maubo',
    'Nailo',
    'Omjon',
    'Pangi-an',
    'Poblacion Occidental',
    'Poblacion Oriental',
    'Simang',
    'Taug',
    'Tausion',
    'Taytay',
    'Ticum',
  ];

  static const List<String> boholMunicipalities = [
    'Tagbilaran',
    'Balilihan',
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'President Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ];

  static const Map<String, List<String>> municipalityBarangays = {
    'Tagbilaran': tagbilaranBarangays,
    'Balilihan': balilihanBarangays,
    'Alburquerque': alburquerqueBarangays,
    'Alicia': aliciaBarangays,
    'Anda': andaBarangays,
    'Antequera': antequeraBarangays,
    'Baclayon': baclayonBarangays,
    'Batuan': batuanBarangays,
    'Bien Unido': bienUnidoBarangays,
    'Bilar': bilarBarangays,
    'Buenavista': buenavistaBarangays,
    'Calape': calapeBarangays,
    'Candijay': candijayBarangays,
    'Carmen': carmenBarangays,
    'Catigbian': catigbianBarangays,
    'Clarin': clarinBarangays,
    'Corella': corellaBarangays,
    'Cortes': cortesBarangays,
    'Dagohoy': dagohoyBarangays,
    'Danao': danaoBarangays,
    'Dauis': dauisBarangays,
    'Dimiao': dimiaoBarangays,
    'Duero': dueroBarangays,
    'Garcia Hernandez': garciaHernandezBarangays,
    'Getafe': getafeBarangays,
    'Guindulman': guindulmanBarangays,
    'Inabanga': inabangaBarangays,
    'Jagna': jagnaBarangays,
    'Lila': lilaBarangays,
    'Loay': loayBarangays,
    'Loboc': lobocBarangays,
    'Loon': loonBarangays,
    'Mabini': mabiniBarangays,
    'Maribojoc': maribojocBarangays,
    'Panglao': panglaoBarangays,
    'Pilar': pilarBarangays,
    'President Carlos P. Garcia': presidentCarlosPGarciaBarangays,
    'Sagbayan': sagbayanBarangays,
    'San Isidro': sanIsidroBarangays,
    'San Miguel': sanMiguelBarangays,
    'Sevilla': sevillaBarangays,
    'Sierra Bullones': sierraBullonesBarangays,
    'Sikatuna': sikatunaBarangays,
    'Talibon': talibonBarangays,
    'Trinidad': trinidadBarangays,
    'Tubigon': tubigonBarangays,
    'Ubay': ubayBarangays,
    'Valencia': valenciaBarangays,
  };

  static List<String> getSortedMunicipalities() {
    final municipalities = boholMunicipalities.toSet().toList();
    municipalities.sort();
    return municipalities;
  }

  static List<String> getBarangaysForMunicipality(String municipality) {
    final barangays = municipalityBarangays[municipality] ?? [];
    final sortedBarangays = barangays.toList()..sort();
    return sortedBarangays;
  }
}
