class LocationConstants {
  static const List<String> tagbilaranBarangays = [
    'Bool',
    'Booy',
    'Cabawan',
    'Cogon',
    'Dampas',
    'Dao',
    'Manga',
    'Mansasa',
    'Poblacion I',
    'Poblacion II',
    'Poblacion III',
    'San Isidro',
    'Taloto',
    'Tiptip',
    'Ubujan',
  ];

  static const List<String> balilihanBarangays = [
    'Baucan Norte',
    'Baucan Sur',
    'Boctol',
    'Boyog Norte',
    'Boyog Proper',
    'Boyog Sur',
    'Cabad',
    'Candasig',
    'Cantalid',
    'Cantomimbo',
    'Cogon',
    'Datag Norte',
    'Datag Sur',
    'Del Carmen Este (DCE) (Poblacion)',
    'Del Carmen Norte (DCN) (Poblacion)',
    'Del Carmen Sur (DCS) (Poblacion)',
    'Del Carmen Weste (DCW) (Poblacion)',
    'Del Rosario',
    'Dorol',
    'Haguilanan Grande',
    'Hanopol Este',
    'Hanopol Norte',
    'Hanopol Weste',
    'Magsija',
    'Maslog',
    'Sagasa',
    'Sal‑ing',
    'San Isidro',
    'San Roque',
    'Santo Niño',
    'Tagustusan',
  ];

  static const List<String> alburquerqueBarangays = [
    'Bahi',
    'San Agustin',
    'Basacdacu',
    'Santa Filomena',
    'Cantiguib',
    'Tagbuane',
    'Dangay',
    'Toril',
    'East Poblacion',
    'West Poblacion',
    'Ponong',
  ];

  static const List<String> aliciaBarangays = [
    'Cambaol',
    'Cayacay',
    'Del Monte',
    'Katipunan',
    'Lumbang',
    'Mahayag',
    'Poblacion',
    'San Isidro',
    'San Jose',
    'San Juan',
    'San Vicente',
    'Santo Niño',
    'Taytay',
  ];

  static const List<String> andaBarangays = [
    'Badiang',
    'Bacong',
    'Bantolinao',
    'Bato',
    'Buenasuerte',
    'Cagting',
    'Candabong',
    'Catagbacan',
    'Lamon',
    'Linawan',
    'Lungsoda-an',
    'Luzaran',
    'Poblacion',
    'Santa Cruz',
    'Talisay',
    'Virgen',
  ];

  static const List<String> antequeraBarangays = [
    'Angilan',
    'Bantolinao',
    'Bicahan',
    'Bitaugan',
    'Bungahan',
    'Canlaas',
    'Cansibuan',
    'Can-omay',
    'Celing',
    'Danao',
    'Danicop',
    'Mag-aso',
    'Poblacion',
    'Quinapon-an',
    'Santo Rosario',
    'Tabuan',
    'Tagubaas',
    'Tupas',
    'Ubojan',
    'Viga',
    'Villa Aurora',
  ];

  static const List<String> baclayonBarangays = [
    'Cambanac',
    'Dasitam',
    'Buenaventura',
    'Guiwanon',
    'Landican',
    'Laya',
    'Libertad',
    'Montana',
    'Pamilacan',
    'Payahan',
    'Poblacion',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Taguihon',
    'Tanday',
  ];

  static const List<String> batuanBarangays = [
    'Alang-alang',
    'Aloja',
    'Behind the Clouds',
    'Bicbica',
    'Bunga',
    'Cagawasan',
    'Garcia',
    'Guinobatan',
    'Quirino',
    'Poblacion',
    'San Isidro',
  ];

  static const List<String> bienUnidoBarangays = [
    'Bacacon',
    'Bacong',
    'Bilbao',
    'Buenavista',
    'Calituban',
    'Dañao',
    'Liberty',
    'Lomangog',
    'Maomawan',
    'Mandawa',
    'Masingin',
    'Pacifico',
    'Pinamgo',
    'Poblacion',
    'Sagasa',
  ];

  static const List<String> bilarBarangays = [
    'Bugang',
    'Cambigsi',
    'Campagao',
    'Cansumbol',
    'Dagohoy',
    'Datag',
    'Ile',
    'Lobgob',
    'Magsija',
    'Nahawan',
    'Owac',
    'Poblacion',
    'Quirino',
    'Rizal',
    'Riverside',
    'Roxas',
    'Subayon',
    'Villa Aurora',
    'Yanaya',
  ];

  static const List<String> buenavistaBarangays = [
    'Bato',
    'Binatuan',
    'Buenavista Norte',
    'Buenavista Sur',
    'Bugaong',
    'Cambangay Norte',
    'Cambangay Sur',
    'Cambuhat',
    'Cangmundo',
    'Cantores',
    'Cantuba',
    'Dait Norte',
    'Dait Sur',
    'Haguilanan',
    'Imelda',
    'Lomangog',
    'Maigang',
    'Malitbog',
    'Manlat',
    'Maslog',
    'Panghagban',
    'Poblacion',
    'Put-ing Bato',
    'Rizal',
    'Rufo Hill',
    'Sabang',
    'San Isidro',
    'San Jose',
    'San Nicolas',
    'San Pascual',
    'Santa Cruz',
    'Santo Niño',
    'Tangkigan',
    'Tubod',
  ];

  static const List<String> calapeBarangays = [
    'Abucayan Norte',
    'Abucayan Sur',
    'Amblag',
    'Angayan Norte',
    'Angayan Sur',
    'Bagacay',
    'Banban',
    'Bentig',
    'Bood',
    'Bual',
    'Cabacungan',
    'Calunasan Norte',
    'Calunasan Sur',
    'Catugasan',
    'Desamparados',
    'Libertad',
    'Limokon Ilaya',
    'Limokon Indangan',
    'Looc',
    'Magtongtong',
    'Manga',
    'Mantatao',
    'Matabao',
    'Poblacion',
    'Sampilang',
    'San Isidro',
    'San Jose',
    'San Vicente',
    'Santa Cruz',
    'Santo Niño',
    'Talisay',
    'Tultugan',
  ];

  static const List<String> candijayBarangays = [
    'Abihilan',
    'Anoling',
    'Boyo-an',
    'Cadapdapan',
    'Cambane',
    'Canawa',
    'Can-olin',
    'Cogtong',
    'La Union',
    'Luan',
    'Lungsodaan',
    'Mahangin',
    'Panadtaran',
    'Poblacion',
    'San Isidro',
    'San Vicente',
    'Santo Niño',
    'Tugas',
    'Tubod',
    'Tugnao',
    'Tupaz',
  ];

  static const List<String> carmenBarangays = [
    'Alegria',
    'Bicao',
    'Bueno Aires',
    'Buenos Aires',
    'Calatrava',
    'El Progreso',
    'Guadalupe',
    'Katipunan',
    'La Libertad',
    'Lumbang',
    'Magsaysay',
    'Mansasa',
    'Montehermoso',
    'Montesuerte',
    'Montevideo',
    'Nueva Fuerza',
    'Nueva Vida Este',
    'Nueva Vida Norte',
    'Nueva Vida Oeste',
    'Poblacion Norte',
    'Poblacion Sur',
    'Quirino',
    'Rizal',
    'San Isidro',
    'San Jose',
    'San Roque',
    'Santa Cruz',
    'Santo Niño',
    'Vallehermoso',
  ];

  static const List<String> catigbianBarangays = [
    'Alegria',
    'Ambuan',
    'Baang',
    'Bagtic',
    'Bongbong',
    'Cambailan',
    'Candumayao',
    'Causwagan Norte',
    'Causwagan Sur',
    'Hagbuaya',
    'Haguilanan',
    'Kang-iras',
    'Libertad Norte',
    'Libertad Sur',
    'Liboron',
    'Mahayag Norte',
    'Mahayag Sur',
    'Maitum',
    'Mantasida',
    'Poblacion',
    'Rizal',
    'Sinakayanan',
  ];

  static const List<String> clarinBarangays = [
    'Aguada',
    'Bacuag',
    'Bonbon',
    'Bugang',
    'Caboy',
    'Cahayag',
    'Canicanian',
    'Cantoyoc',
    'Causwagan',
    'Dagohoy',
    'Dakit',
    'Danahao',
    'Katipunan',
    'Lajog',
    'Lico-an',
    'Lumbac',
    'Macalingan',
    'Poblacion Centro',
    'Poblacion Norte',
    'Poblacion Sur',
    'Riverside',
    'Santo Niño',
    'Tangaran',
    'Tontonan',
  ];

  static const List<String> corellaBarangays = [
    'Alegria',
    'Anislag',
    'Bacani',
    'Canangca-an',
    'Canapnapan',
    'Catugasan',
    'Poblacion',
    'Tungod',
  ];

  static const List<String> cortesBarangays = [
    'De La Paz',
    'Fatima',
    'Loreto',
    'Lourdes',
    'Malayo Norte',
    'Malayo Sur',
    'Mansasa',
    'Montserrat',
    'Patrocinio',
    'Poblacion',
    'Rizal',
    'Rosario',
    'Salvador',
    'San Roque',
  ];

  static const List<String> dagohoyBarangays = [
    'Babag',
    'Caluasan',
    'Candelaria',
    'Candaog',
    'Can-oling',
    'Casanayan',
    'Estaca',
    'La Victoria',
    'Mahayag',
    'Poblacion',
    'Rizal',
    'San Miguel',
    'San Vicente',
    'Santa Cruz',
    'Villa Anunciado',
  ];

  static const List<String> danaoBarangays = [
    'Cabatuan',
    'Cagawitan',
    'Candasig',
    'Cangmundo',
    'Cantubod',
    'Concepcion',
    'Dagohoy',
    'Hibale',
    'Mabuhay Cabatuan',
    'Nahud',
    'Poblacion',
    'Remedios',
    'San Carlos',
    'San Miguel',
    'Santa Fe',
    'Santo Niño',
    'Villa Anunciado',
  ];

  static const List<String> dauisBarangays = [
    'Biking',
    'Bingag',
    'Catarman',
    'Dao',
    'Mayacabac',
    'Mariveles',
    'Poblacion',
    'San Isidro',
    'Songculan',
    'Tabalong',
    'Tinago',
    'Totolan',
  ];

  static const List<String> dimiaoBarangays = [
    'Abihid',
    'Alemania',
    'Baguhan',
    'Bakilid',
    'Balbalan',
    'Banban',
    'Bauhugan',
    'Bilisan',
    'Cabagakian',
    'Cabanbanan',
    'Cadap-agan',
    'Cambacol',
    'Cambayaon',
    'Canhayupon',
    'Canlambong',
    'Casingan',
    'Catugasan',
    'Datag',
    'Guindaguitan',
    'Guingoyuran',
    'Ile',
    'Lapsaon',
    'Limokon Ilaod',
    'Limokon Ilaya',
    'Luyo',
    'Malijao',
    'Oac',
    'Pagsa',
    'Pangihawan',
    'Puangyuta',
    'Sawang',
    'Tangohay',
    'Taongon Cabatuan',
    'Taongon Can-andam',
    'Tawid Bitaog',
  ];

  static const List<String> dueroBarangays = [
    'Alejawan',
    'Angilan',
    'Bangwalog',
    'Camba-ol',
    'Camagong',
    'Cansuhay',
    'Colonia',
    'Duay',
    'Jao',
    'Langkis',
    'Madua Norte',
    'Madua Sur',
    'Mambool',
    'Mawi',
    'Payao',
    'Poblacion',
    'San Antonio',
    'San Isidro',
    'Santa Cruz',
    'Taytay',
    'Tubod',
  ];

  static const List<String> garciaHernandezBarangays = [
    'Abijilan',
    'Antipolo',
    'Basiao',
    'Baybay',
    'Cambuyo',
    'Canayaon East',
    'Canayaon West',
    'Candanas',
    'Candulao',
    'Catmon',
    'Cayam',
    'Cupa',
    'Datag',
    'Estaca',
    'Libertad',
    'Lungsodaan East',
    'Lungsodaan West',
    'Malinao',
    'Manaba',
    'Pasong',
    'Poblacion East',
    'Poblacion West',
    'Sacaon',
    'Sampong',
    'Tabuan',
    'Togbongon',
    'Ulbujan East',
    'Ulbujan West',
    'Victoria',
    'Santo Niño',
  ];

  static const List<String> getafeBarangays = [
    'Alumar',
    'Banacon',
    'Buyog',
    'Cabasakan',
    'Campao Occidental',
    'Campao Oriental',
    'Cangmundo',
    'Handumon',
    'Jagoliao',
    'Jandayan Norte',
    'Jandayan Sur',
    'Mahanay Island',
    'Mahanay Norte',
    'Mahanay Sur',
    'Nasingin',
    'Pandanon',
    'Poblacion',
    'Saguise',
    'Salog',
    'San Jose',
    'Santa Cruz',
    'Santo Niño',
    'Taytay',
    'Tugas',
  ];

  static const List<String> guindulmanBarangays = [
    'Basdio',
    'Bato',
    'Bayong',
    'Biabas',
    'Bulawan',
    'Cabantian',
    'Canhaway',
    'Cansiwang',
    'Casbu',
    'Catungawan Norte',
    'Catungawan Sur',
    'Guinacot',
    'Guio-ang',
    'Lombog',
    'Mayuga',
    'Poblacion Sawang',
    'Poblacion Tabajan',
    'Tabunok',
    'Trinidad',
  ];

  static const List<String> inabangaBarangays = [
    'Abaca',
    'Anas',
    'Asinan',
    'Banahao',
    'Bonotbonot',
    'Bugang',
    'Cabad',
    'Cagawasan',
    'Cagayan',
    'Camayaan',
    'Cambitoon',
    'Canmangao',
    'Cantuhog',
    'Casilay',
    'Dagnawan',
    'Dagohoy',
    'Datag',
    'Fatima',
    'General',
    'Ilihan Norte',
    'Ilihan Sur',
    'Lapacan Norte',
    'Lapacan Sur',
    'Luyo',
    'Lutao',
    'Mahayag',
    'Nabuad',
    'Pahangog',
    'Panadtaran',
    'Poblacion',
    'Quinoguitan',
    'Rizal',
    'San Isidro',
    'San Jose',
    'San Miguel',
    'San Roque',
    'Santa Ana',
    'Santa Cruz',
    'Santa Fe',
    'Santa Filomena',
    'Santo Niño',
    'Sindangan',
    'Suba',
    'Tagnacioc',
    'Tawid',
    'U-og',
    'Ubay Island',
    'Ubujan',
    'Villa Kali',
  ];

  static const List<String> jagnaBarangays = [
    'Alejawan',
    'Balili',
    'Boctol',
    'Buyog',
    'Bunga Ilaya',
    'Bunga Mar',
    'Cabungaan',
    'Calabacita',
    'Cambugason',
    'Can-upao',
    'Can-ipol',
    'Canjulao',
    'Cantagay',
    'Cantuyoc',
    'Can-uba',
    'Can-upao',
    'Faraon',
    'Ipil',
    'Kinagbaan',
    'Laca',
    'Larapan',
    'Lonoy',
    'Looc',
    'Malbog',
    'Mayana',
    'Naatang',
    'Nausok',
    'Odiong',
    'Pagina',
    'Pangdan',
    'Poblacion (Pondol)',
    'Tejero',
    'Tubod Mar',
    'Tubod Monte',
  ];

  static const List<String> lilaBarangays = [
    'Bagacay',
    'Cahayag',
    'Calvario',
    'Candulang',
    'Catugasan',
    'Cayupo',
    'Cogon',
    'Genoveva',
    'Jalija',
    'Macalingan',
    'Malinao East',
    'Malinao West',
    'Nagsulay',
    'Pagahat',
    'Poblacion',
    'Taug',
    'Taytay',
    'Tubod',
  ];

  static const List<String> loayBarangays = [
    'Agape',
    'Alegria',
    'Balt',
    'Bonga Ilaya',
    'Bonga Mar',
    'Buenavista',
    'Calvario',
    'Catarman',
    'Concepcion',
    'Hinawanan',
    'Las Salinas Norte',
    'Las Salinas Sur',
    'Lila',
    'Napo',
    'Palo',
    'Poblacion Ibaba',
    'Poblacion Ilaya',
    'Poblacion Ubos',
    'Sagnap',
    'Tangcasan Norte',
    'Tangcasan Sur',
    'Tayong',
    'Tugas',
    'Villalimpia',
  ];

  static const List<String> lobocBarangays = [
    'Agape',
    'Bagumbayan',
    'Bahi-an',
    'Bahi',
    'Bil-isan',
    'Bonbon',
    'Bugho',
    'Bungahan',
    'Busay',
    'Calunasan Norte',
    'Calunasan Sur',
    'Camayaan',
    'Candasagan',
    'Gon-ob',
    'Gongonan',
    'Gotozon',
    'Jimilian',
    'Mag-Aso',
    'Nueva Vida',
    'Oy',
    'Poblacion Sawang',
    'Poblacion Ubos',
    'Quinoguitan',
    'Sabac',
    'Sohoton',
    'Tanday',
    'Tapon',
    'Ubojan',
  ];

  static const List<String> loonBarangays = [
    'Agahay',
    'Agsoso',
    'Angilan',
    'Badbad',
    'Bahi',
    'Boctol',
    'Bonbon',
    'Bongco',
    'Bood',
    'Bugho',
    'Cabug',
    'Cambaquiz',
    'Candaigan',
    'Canhangdon Este',
    'Canhangdon Oeste',
    'Canmaag',
    'Canugao',
    'Cantam-is Bago',
    'Cantam-is Baslay',
    'Cantumog',
    'Cogon Norte',
    'Cogon Sur',
    'Cuasi',
    'Garcia',
    'Genonocan',
    'Guisangon',
    'Jampang',
    'Lagtangon',
    'Langkis',
    'Lawa-an',
    'Lintuan',
    'Looc',
    'Mabog',
    'Maano',
    'Magyang',
    'Mahayag',
    'Matabao',
    'Mocpoc Norte',
    'Mocpoc Sur',
    'Moto',
    'Napo',
    'Nan-od',
    'Nueva Vida',
    'Pandan',
    'Pantudlan',
    'Poblacion',
    'Quinob-an',
    'Quinoguitan',
    'Sagsagat',
    'Santa Cruz',
    'Santa Fe',
    'Santo Niño',
    'Santo Rosario',
    'Sebac',
    'Songculan',
    'Suba',
    'Tangnan',
    'Taytay',
    'Tontonan',
    'Tubodacu',
    'Tubod Mar',
    'Tubod Monte',
    'Tubod Sur',
    'Ubojan',
  ];

  static const List<String> mabiniBarangays = [
    'Abaca',
    'Aguipo',
    'Bahaybahay',
    'Bahuan',
    'Baliwagan',
    'Baybayon',
    'Bood',
    'Bulongan',
    'Cabatang',
    'Cabidian',
    'Camias',
    'Concepcion',
    'Lungsoda-an',
    'Paraiso',
    'Poblacion I',
    'Poblacion II',
    'San Isidro',
    'San Jose',
    'San Roque',
    'Tambo',
    'Tambis',
    'Tungod',
  ];

  static const List<String> maribojocBarangays = [
    'Aghao',
    'Aliguay',
    'Anislag',
    'Atabay',
    'Bayacabac',
    'Bood',
    'Busao',
    'Cabawan',
    'Candavid',
    'Dipatlong',
    'Guiwanon',
    'Jandig',
    'Lagtangon',
    'Pagnitoan',
    'Panghayaan',
    'Poblacion',
    'Pondol',
    'Punsod',
    'Puntod',
    'San Isidro',
    'San Roque',
    'Tinibgan',
  ];

  static const List<String> panglaoBarangays = [
    'Bil-isan',
    'Bingag',
    'Bolod',
    'Danao',
    'Doljo',
    'Looc',
    'Libaong',
    'Poblacion',
    'Tawala',
    'Tabalong',
  ];

  static const List<String> pilarBarangays = [
    'Aurora',
    'Bagacay',
    'Bagumbayan',
    'Balilihan',
    'Bayong',
    'Cabulihan',
    'Catagdaan',
    'Del Pilar',
    'Inaghuban',
    'La Hacienda',
    'Lundag',
    'Magsaysay',
    'New Village',
    'Pamacsalan',
    'Poblacion',
    'Rizal',
    'San Carlos',
    'San Isidro',
    'San Vicente',
    'Santa Fe',
    'Villa Anunciado',
  ];

  static const List<String> presidentCarlosPGarciaBarangays = [
    'Aguining',
    'Basiao',
    'Bogo',
    'Bonbonon',
    'Campao Occidental',
    'Campao Oriental',
    'Canmangao',
    'Gaus',
    'Hinlayagan Ilaya',
    'Hinlayagan Norte',
    'Hinlayagan Sur',
    'Lapinig',
    'Lipata',
    'Mahanay',
    'Mahayag',
    'Poblacion',
    'Popoo',
    'Saguise',
    'San Jose',
    'San Vicente',
    'Santa Cruz',
    'Tilmobo',
    'Tugnao',
  ];

  static const List<String> sagbayanBarangays = [
    'Cabatacan',
    'Cagawasan',
    'Calangahan',
    'Canmaya Centro',
    'Canmaya Diot',
    'Canmanoc',
    'Cansibao',
    'Dagnawan',
    'Dait Norte',
    'Dait Sur',
    'Katipunan',
    'Libertad Norte',
    'Libertad Sur',
    'Mabuhay',
    'Poblacion',
    'Poblacion Ilaya',
    'Poblacion Ubos',
    'San Agustin',
    'San Isidro',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Santo Niño',
    'Sigcahan',
  ];

  static const List<String> sanIsidroBarangays = [
    'Abehilan',
    'Baunos',
    'Baryong Daan',
    'Caimbang',
    'Cambansag',
    'Cansague Norte',
    'Cansague Sur',
    'Causwagan Sur',
    'Masonoy',
    'Poblacion',
    'Sampong',
    'Talamban',
  ];

  static const List<String> sanMiguelBarangays = [
    'Bayongan',
    'Bugang',
    'Cabangahan',
    'Cambangay Norte',
    'Cambangay Sur',
    'Camanaga',
    'Capayas',
    'Corazon',
    'Garcia',
    'Hagbuyo',
    'Kagawasan',
    'Mahayag',
    'Poblacion',
    'San Isidro',
    'San Jose',
    'San Vicente',
    'Santo Niño',
    'Tomoc',
  ];

  static const List<String> sevillaBarangays = [
    'Bayawahan',
    'Cabancalan',
    'Calbasa',
    'Calvario',
    'Cambagahan',
    'Candabong',
    'Concepcion',
    'Ewon',
    'Ginopolan',
    'Lagtangon',
    'Magsaysay',
    'Poblacion',
    'Sikatuna',
  ];

  static const List<String> sierraBullonesBarangays = [
    'Abachanan',
    'Anibongan',
    'Cagawasan',
    'Cahayag',
    'Canlangit',
    'Casilay',
    'Danicop',
    'Dumalogdog',
    'Dusita',
    'Guadalupe',
    'La Union',
    'Libertad',
    'Mantalongon',
    'Poblacion',
    'Salvador',
    'San Agustin',
    'San Isidro',
    'San Jose',
    'Santa Cruz',
    'Valaga',
    'Villa Garcia',
    'Villahermosa',
  ];

  static const List<String> sikatunaBarangays = [
    'Abucay Norte',
    'Abucay Sur',
    'Badiang',
    'Cambu-ac',
    'Cambagui',
    'Cangmundo',
    'Libertad',
    'Poblacion I',
    'Poblacion II',
    'Talisay',
  ];

  static const List<String> talibonBarangays = [
    'Bagacay',
    'Balintawak',
    'Balintawak Norte',
    'Balintawak Sur',
    'Bantigue',
    'Bil-isan',
    'Burgos',
    'Calituban',
    'Cambangay Norte',
    'Cambangay Sur',
    'Cataban',
    'Guinacot',
    'Magsaysay',
    'Nocnocan',
    'Poblacion',
    'Rizal',
    'San Agustin',
    'San Carlos',
    'San Jose',
    'San Pedro',
    'San Roque',
    'San Salvador',
    'Santa Emilia',
    'Santa Fe',
    'Suba',
  ];

  static const List<String> trinidadBarangays = [
    'Banlasan',
    'Banahao',
    'Bongbong',
    'Boyongan',
    'Cahayag',
    'Hinlayagan Ilaud',
    'Hinlayagan Ilaya',
    'Kauswagan',
    'La Union',
    'Mabuhay Cabigohan',
    'Madua Norte',
    'Madua Sur',
    'Poblacion',
    'San Isidro',
    'San Jose',
    'San Vicente',
    'Santo Niño',
    'Sikatuna',
    'Tagum Norte',
    'Tagum Sur',
  ];

  static const List<String> tubigonBarangays = [
    'Bagongbanwa',
    'Bagacay',
    'Bahay',
    'Bilangbilangan Daku',
    'Bilangbilangan Diot',
    'Bosongon',
    'Buenos Aires',
    'Bunacan',
    'Cahayag',
    'Cawayanan',
    'Centro',
    'Genonocan',
    'Ilihan Norte',
    'Ilihan Sur',
    'Libertad',
    'Macaas',
    'Mahayag',
    'Matabao',
    'Panaytayon',
    'Pangapasan',
    'Pinayagan Norte',
    'Pinayagan Sur',
    'Poblacion',
    'Potohan',
    'Tan-awan',
    'Talisay',
    'Tawid',
    'Tinangnan',
    'Ubay Island',
    'Ubojan',
    'Ulbujan',
    'Utanan Norte',
    'Utanan Sur',
  ];

  static const List<String> ubayBarangays = [
    'Achila',
    'Bay-ang',
    'Benliw',
    'Biabas',
    'Bood',
    'Buenos Aires',
    'Bulilis',
    'Cabatuan',
    'Calanggaman',
    'California',
    'Camali-an',
    'Camanaga',
    'Casate',
    'Cuya',
    'Fatima',
    'Gabi',
    'Governor Boyles',
    'Hambabauran',
    'Humayhumay',
    'Ilihan',
    'Juagdan',
    'Kagawasan',
    'Kamagong',
    'Lamigan',
    'Lomangog',
    'Los Angeles',
    'Lusong',
    'Mahayag',
    'Pag-asa',
    'Pangpang',
    'Poblacion',
    'San Francisco',
    'San Isidro',
    'San Pascual',
    'Sentinila',
    'Sinandigan',
    'Tapal',
    'Tapon',
    'Tintinan',
    'Tipolo',
    'Union',
    'Villa Teresita',
    'Zamora',
  ];

  static const List<String> valenciaBarangays = [
    'Abaca',
    'Anas',
    'Anoyon',
    'Balingasao',
    'Banban',
    'Bato',
    'Bay-ang',
    'Canmanico',
    'Canlusong',
    'Cansibao',
    'Catugasan',
    'Cawayanan',
    'Genonocan',
    'Jubang',
    'Lantang',
    'Laurente',
    'La Victoria',
    'Limokon Ilaya',
    'Limokon Oeste',
    'Looc',
    'Lumbay',
    'Lutao',
    'Magsaysay',
    'Manapol',
    'Nagsulay',
    'Omjon',
    'Pandan',
    'Poblacion Occidental',
    'Poblacion Oriental',
    'Sacaon',
    'San Agustin',
    'San Isidro',
    'Santa Cruz',
    'Santo Niño',
    'Tauson',
  ];

  static const List<String> boholMunicipalities = [
    'Tagbilaran',
    'Balilihan',
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'President Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ];

  static const Map<String, List<String>> municipalityBarangays = {
    'Tagbilaran': tagbilaranBarangays,
    'Balilihan': balilihanBarangays,
    'Alburquerque': alburquerqueBarangays,
    'Alicia': aliciaBarangays,
    'Anda': andaBarangays,
    'Antequera': antequeraBarangays,
    'Baclayon': baclayonBarangays,
    'Batuan': batuanBarangays,
    'Bien Unido': bienUnidoBarangays,
    'Bilar': bilarBarangays,
    'Buenavista': buenavistaBarangays,
    'Calape': calapeBarangays,
    'Candijay': candijayBarangays,
    'Carmen': carmenBarangays,
    'Catigbian': catigbianBarangays,
    'Clarin': clarinBarangays,
    'Corella': corellaBarangays,
    'Cortes': cortesBarangays,
    'Dagohoy': dagohoyBarangays,
    'Danao': danaoBarangays,
    'Dauis': dauisBarangays,
    'Dimiao': dimiaoBarangays,
    'Duero': dueroBarangays,
    'Garcia Hernandez': garciaHernandezBarangays,
    'Getafe': getafeBarangays,
    'Guindulman': guindulmanBarangays,
    'Inabanga': inabangaBarangays,
    'Jagna': jagnaBarangays,
    'Lila': lilaBarangays,
    'Loay': loayBarangays,
    'Loboc': lobocBarangays,
    'Loon': loonBarangays,
    'Mabini': mabiniBarangays,
    'Maribojoc': maribojocBarangays,
    'Panglao': panglaoBarangays,
    'Pilar': pilarBarangays,
    'President Carlos P. Garcia': presidentCarlosPGarciaBarangays,
    'Sagbayan': sagbayanBarangays,
    'San Isidro': sanIsidroBarangays,
    'San Miguel': sanMiguelBarangays,
    'Sevilla': sevillaBarangays,
    'Sierra Bullones': sierraBullonesBarangays,
    'Sikatuna': sikatunaBarangays,
    'Talibon': talibonBarangays,
    'Trinidad': trinidadBarangays,
    'Tubigon': tubigonBarangays,
    'Ubay': ubayBarangays,
    'Valencia': valenciaBarangays,
  };

  static List<String> getSortedMunicipalities() {
    final municipalities = boholMunicipalities.toSet().toList();
    municipalities.sort();
    return municipalities;
  }

  static List<String> getBarangaysForMunicipality(String municipality) {
    final barangays = municipalityBarangays[municipality] ?? [];
    final sortedBarangays = barangays.toList()..sort();
    return sortedBarangays;
  }
}
